### ISSUE TITLE
Problem in kipp plots

### ISSUE THREAD

**Issue by kao25** [orlox/mkipp#1]
Hi 
I am trying to get a kipp plot but i have this error. 

Reading profile data
("Couldn't read profile LOGS/profile1.data", KeyError('eps_nuc',))
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    mkipp.kipp_plot(mkipp.Kipp_Args())
  File "/home/mesa-saa/Downloads/mkipp-master/mkipp.py", line 189, in kipp_plot
    xyz_data = get_xyz_data(profile_paths, kipp_args, xlims = xlims)
  File "/home/mesa-saa/Downloads/mkipp-master/kipp_data.py", line 335, in get_xyz_data
    y_data = prof.get('mass')
  File "/home/mesa-saa/Downloads/mkipp-master/mesa_data.py", line 75, in get
    return self.data[key]
AttributeError: Mesa_Data instance has no attribute 'data'
******************************************************************************************
********************************************************************

I don't know why ? 

I have added mixing regions and mix_relr.

Can any one give me an advice

I used exactly the same code in the website   example.py

Thanks !

**Comment by orlox** [comment]
Hi Kao,

From the guthub readme:

IMPORTANT!! your history_columns.list needs to have mixing_regions and
mix_relr_regions specified for MESA to output the neccesary data of the
mixing regions in terms of mass and radius respectively. Also, newer
versions of MESA include significantly less output in the profile files, so
values such as eps_nuc need to be added to profile_columns.list as well.

See the last sentence. The latest mesa versions have less data by default.
You need to include eps_nuc as well.

Cheers

On Dec 21, 2017 9:33 PM, "kao25" <notifications@github.com> wrote:

Hi
I am trying to get a kipp plot but i have this error.

Reading profile data
("Couldn't read profile LOGS/profile1.data", KeyError('eps_nuc',))
Traceback (most recent call last):
File "example.py", line 10, in
mkipp.kipp_plot(mkipp.Kipp_Args())
File "/home/mesa-saa/Downloads/mkipp-master/mkipp.py", line 189, in
kipp_plot
xyz_data = get_xyz_data(profile_paths, kipp_args, xlims = xlims)
File "/home/mesa-saa/Downloads/mkipp-master/kipp_data.py", line 335, in
get_xyz_data
y_data = prof.get('mass')
File "/home/mesa-saa/Downloads/mkipp-master/mesa_data.py", line 75, in get
return self.data[key]
AttributeError: Mesa_Data instance has no attribute 'data'
------------------------------
------------------------------

I don't know why ?

I have added mixing regions and mix_relr.

Can any one give me an advice

I used exactly the same code in the website example.py

Thanks !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/orlox/mkipp/issues/1>, or mute the thread
