### ISSUE TITLE
Convective region extending beyond total mass of the star

### ISSUE THREAD

**Issue by poojanagrawal** [orlox/mkipp#3]
Hi, 
I am having slight trouble with convective regions in my plots.
In the attached plot, there is an extra convective and overshooting region, some of which also extends beyond the total mass of the star.  
I have also encountered this problem with stars of other masses. 
My history files include following data regarding mixing regions

```
       mixing_regions 20 
       mix_relr_regions 20
       burning_regions 20
```
![Kippenhahn_time](https://user-images.githubusercontent.com/34255053/72232918-561bd100-3618-11ea-9325-d48d6659670a.png)

Can you help me with what could be missing/wrong here?

Thanks,
Poojan

**Comment by orlox** [comment]
Hi!

that definitely looks like a mess. It's hard for me to evaluate the root cause without the exact inputs used for this simulation. Could you provide me with your inlists and MESA version to reproduce this simulation? You can also include your history.data as well to verify I'm getting the same results from the simulation.

Cheers

**Comment by poojanagrawal** [comment]
Hi Pablo,

I think I figured out the issue. I have two history files for output. One for Pre-Main sequence and other for the rest of the evolution. I just wanted to plot the evolution beyond PreMS but unknowingly the code was using both files and so the error. PreMS history file was getting overplotted on top of rest. Making sure only one history file is used solves the problem. 

Sorry for the trouble.

Thanks,
Poojan
